apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonarqube-pv
  namespace: sonarqube
spec:
  storageClassName: sonarqube-pv
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 3Gi
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/sonarqube-volume/

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: sonarqube-pv
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer