FROM maven:3.9.10-eclipse-temurin-21 AS BUILD_IMAGE

# Install wget and unzip
RUN apt-get update && apt-get install -y wget unzip && rm -rf /var/lib/apt/lists/*

RUN wget https://github.com/hkhcoder/vprofile-project/archive/refs/heads/local.zip && \
    unzip local.zip && \
    mv vprofile-project-local vprofile-project

RUN cd vprofile-project && mvn install

FROM tomcat:10-jdk21

RUN rm -rf /usr/local/tomcat/webapps/*

COPY --from=BUILD_IMAGE vprofile-project/target/vprofile-v2.war /usr/local/tomcat/webapps/ROOT.war

EXPOSE 8080
CMD ["catalina.sh", "run"]