apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pre-gitops
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/TrieuBui1012/lakehouse.git
    targetRevision: HEAD
    path: argocd/pre-gitops
  destination:
    server: https://kubernetes.default.svc
    namespace: gitops
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true