apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jenkins-helm
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/TrieuBui1012/lakehouse.git
    targetRevision: HEAD
    path: jenkins/jenkins
    helm:
      releaseName: jenkins
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: jenkins
  syncPolicy:
    syncOptions:
      - Prune=false
      - CreateNamespace=true
      - UseHelmInstall=true