apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgresql-sonarqube-helm
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/TrieuBui1012/lakehouse.git
    targetRevision: HEAD
    path: sonarqube/postgresql
    helm:
      releaseName: postgresql-sonarqube
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: sonarqube
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - UseHelmInstall=true
      - ApplyOutOfSyncOnly=true